name: DaisyVotes
version: '1.3'
main: cat.daisy.daisyVotes.DaisyVotes
api-version: '1.21'
authors: [Daisy]
description: Simple But Working Vote/Voteparty Plugin
website: https://daisy.cat
depend: [Votifier]
softdepend: [PlaceholderAPI]
folia-supported: true
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.50.3.0
  - org.jetbrains.exposed:exposed-core:0.61.0
  - org.jetbrains.exposed:exposed-jdbc:0.61.0